### ISSUE TITLE
Travis build on Python 2.6 fails

### ISSUE THREAD

**Issue by maeck70** [maeck70/iritop#22]
```
python iritop.py --test --node http://xxx:14265
Traceback (most recent call last):
  File "iritop.py", line 11, in <module>
    from subprocess import check_output
ImportError: cannot import name check_output
The command "python iritop.py --test --node http://xxx:14265" exited with 1.
```

Its a bit odd, subprocess.check_output should be part of Python since 2.5
However, to be honest, Python 2.6 is no longer supported by the Python team.

**Comment by maeck70** [comment]
2.6 has been taken off the supported list.
